/*
 * File generated by Test generator (dotup.dotup-vscode-test-generator)
 * Date: 2019-03-19 02:24:28
 */
import { expect } from 'chai'
import { App } from './app'
import express from 'express'
import bodyParser from 'body-parser'
import axios from 'axios'
import { Request, Response } from 'express'
import _ from 'lodash'
import _error from '../_src/_error'
import { NextFunction } from 'connect'

describe('Test class App', () => {
    it('App-url', () => {
        // Arguments
        const props1 = undefined
        const url1 = 'Oha'

        // Property call
        const app = new App(props1)
        app.url = url1
        const result = app.url

        // Expect result
        expect(result).equals(url1)
    })

    it('App-routes', () => {
        // Arguments
        const props2 = undefined
        const routes1 = undefined

        // Property call
        const app = new App(props2)
        app.routes = routes1
        const result = app.routes

        // Expect result
        expect(result).equals(routes1)
    })

    it('App-app', () => {
        // Arguments
        const props3 = undefined
        const app1 = undefined

        // Property call
        const app = new App(props3)
        app.app = app1
        const result = app.app

        // Expect result
        expect(result).equals(app1)
    })
})
